// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryManagement.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public int? CategoryId { get; set; }

    public int? SupplierId { get; set; }

    public int? Quantity { get; set; }

    public DateOnly? LastUpdated { get; set; }

    public decimal? Price { get; set; }

    public virtual Category Category { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}