// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryManagement.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int? ProductId { get; set; }

    public string TransactionType { get; set; }

    public int? Quantity { get; set; }

    public DateOnly? TransactionDate { get; set; }

    public virtual Product Product { get; set; }
}